#include "Teensy_ClockConfig.h"

void Configure_PLL_CLK(void) {

    PLL_ARM_CLK_Init();
    PLL_SYS_CLK_Init();
    PLL_USB1_CLK_Init();
    PLL_VIDEO_CLK_Init();

    USDHC1_CLK_Init();
    USDHC2_CLK_Init();
    CSI_CLK_Init();
    LPSPI_CLK_Init();
    TRACE_CLK_Init();
    LPI2C_CLK_Init();
    CAN_CLK_Init();
    UART_CLK_Init();
    LCDIF_CLK_Init();

    OpenCloks();

    __DSB();
    __ISB();

}

void OpenCloks(void) {
    CCM->CCGR0 |= 0xFFFFFFFF;
    CCM->CCGR1 |= 0xFFFFFFFF;
    CCM->CCGR2 |= 0xFC3FFFFF;
    CCM->CCGR3 |= 0xFFFFFFCF;
    CCM->CCGR4 |= 0xFFFFFFFF;
    CCM->CCGR5 |= 0xFFFFFFFF;
    CCM->CCGR6 |= 0xFFFFFFFF;
    CCM->CCGR7 |= 0x00003FFF;
}

void PLL_ARM_CLK_Init(void) {

    // AHB, IPG ve PERCLK saat kaynaklarini PLL_ARM'den OSC'ye cevir.
    CCM->CSCMR1 = ( CCM->CSCMR1 & ~CCM_CSCMR1_PERCLK_CLK_SEL_MASK ) | CCM_CSCMR1_PERCLK_CLK_SEL(1);

    if(!(CCM->CBCDR & CCM_CBCDR_PERIPH_CLK_SEL_MASK)) {
        if(((CCM->CBCDR & CCM_CBCDR_PERIPH_CLK2_PODF_MASK) != CCM_CBCDR_PERIPH_CLK2_PODF(0))) {
            CCM->CBCDR = ( CCM->CBCDR & ~CCM_CBCDR_PERIPH_CLK2_PODF_MASK ) | CCM_CBCDR_PERIPH_CLK2_PODF(0);
            (void)CCM->CBCDR;
        }

        CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_PERIPH_CLK2_SEL_MASK ) | CCM_CBCMR_PERIPH_CLK2_SEL(1); // OSC'ye gec.
        while (CCM->CDHIPR & CCM_CDHIPR_PERIPH2_CLK_SEL_BUSY_MASK){};

        CCM->CBCDR = ( CCM->CBCDR & ~CCM_CBCDR_PERIPH_CLK_SEL_MASK ) | CCM_CBCDR_PERIPH_CLK_SEL(1); // PERIPH_CLK2'ye gec.
        while (CCM->CDHIPR & CCM_CDHIPR_PERIPH_CLK_SEL_BUSY_MASK){};
    }
    
    // PLL_ARM ayari
    CCM_ANALOG->PLL_ARM = CCM_ANALOG_PLL_ARM_POWERDOWN_MASK;
    CCM_ANALOG->PLL_ARM = CCM_ANALOG_PLL_ARM_ENABLE_MASK | CCM_ANALOG_PLL_ARM_DIV_SELECT(88); // ( 24MHz * 88/2 = 1056MHz)

    CCM->CACRR = CCM_CACRR_ARM_PODF(1); // ( 1056MHz / 2 = 528MHz )
	while (CCM->CDHIPR & CCM_CDHIPR_ARM_PODF_BUSY_MASK) ;

    // AHB clock ayari
    CCM->CBCDR = ( CCM->CBCDR & ~CCM_CBCDR_AHB_PODF_MASK ) | CCM_CBCDR_AHB_PODF(3); // ( 528MHz / 4 = 132MHz )
    while (CCM->CDHIPR & CCM_CDHIPR_AHB_PODF_BUSY_MASK){}

    //IPG clock ayari
    CCM->CBCDR = ( CCM->CBCDR & ~CCM_CBCDR_IPG_PODF_MASK ) | CCM_CBCDR_IPG_PODF(2); // ( 132MHz / 3 = 44MHz )
    (void)CCM->CBCDR;

    //PERCLK clock ayari
    CCM->CSCMR1 = ( CCM->CSCMR1 & ~CCM_CSCMR1_PERCLK_PODF_MASK ) | CCM_CSCMR1_PERCLK_PODF(0); // ( 44MHz / 1 = 44MHz )
    (void)CCM->CSCMR1;

    // AHB, IPG ve PERCLK saat ayarlarinin kaynağını OSC'den PLL_ARM'ye cevir.
    if((CCM->CBCMR & CCM_CBCMR_PRE_PERIPH_CLK_SEL_MASK) != CCM_CBCMR_PRE_PERIPH_CLK_SEL(3)) {
        CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_PRE_PERIPH_CLK_SEL_MASK ) | CCM_CBCMR_PRE_PERIPH_CLK_SEL(3); // PLL1'i PER_PERIPH olarak sec.
        (void)CCM->CBCMR;
    }

    CCM->CBCDR = ( CCM->CBCDR & ~CCM_CBCDR_PERIPH_CLK_SEL_MASK ) | CCM_CBCDR_PERIPH_CLK_SEL(0); // PRE_PERIPH( PLL1 )'e gec.
    while (CCM->CDHIPR & CCM_CDHIPR_PERIPH_CLK_SEL_BUSY_MASK){};

    CCM->CSCMR1 = ( CCM->CSCMR1 & ~CCM_CSCMR1_PERCLK_CLK_SEL_MASK ) | CCM_CSCMR1_PERCLK_CLK_SEL(0); // OSC'den IPG'ye gec
    (void)CCM->CSCMR1;

}
void PLL_SYS_CLK_Init(void) {

    // PLL2 altindaki saatler. PLL2 PowerDown oncesi set etmek gerekiyor
    CCM_ANALOG->PFD_528_SET = CCM_ANALOG_PFD_528_PFD0_CLKGATE_MASK | CCM_ANALOG_PFD_528_PFD1_CLKGATE_MASK | 
                              CCM_ANALOG_PFD_528_PFD2_CLKGATE_MASK | CCM_ANALOG_PFD_528_PFD3_CLKGATE_MASK ;

    if(!(CCM_ANALOG->PLL_SYS & CCM_ANALOG_PLL_SYS_DIV_SELECT_MASK)) {
        CCM_ANALOG->PLL_SYS_SET = CCM_ANALOG_PLL_SYS_BYPASS_MASK | CCM_ANALOG_PLL_SYS_POWERDOWN_MASK; // PLL bypass enable ve PLL'i Kapat

        CCM_ANALOG->PLL_SYS_CLR = CCM_ANALOG_PLL_SYS_DIV_SELECT_MASK;
        CCM_ANALOG->PLL_SYS_SET = CCM_ANALOG_PLL_SYS_DIV_SELECT(1); // Carpan Degeri Ayari ( 24MHz * 22 = 528MHz )
        
        // PFD_528_FRAC Set ( PFDn ->  528MHz * 18 / FRAC )
        // ( PFD0 = 352MHz ), (  PFD1 = 594MHz ), (  PFD2 = 396MHz ), (  PFD3 = 297MHz )
        CCM_ANALOG->PFD_528 = CCM_ANALOG_PFD_528_PFD0_FRAC(27) | CCM_ANALOG_PFD_528_PFD1_FRAC(16) | 
                              CCM_ANALOG_PFD_528_PFD2_FRAC(24) | CCM_ANALOG_PFD_528_PFD3_FRAC(32) | 0x80808080;

        CCM_ANALOG->PLL_SYS_CLR = CCM_ANALOG_PLL_SYS_POWERDOWN_MASK; // PLL'e Guc Ver

        CCM_ANALOG->PLL_SYS_SET = CCM_ANALOG_PLL_SYS_ENABLE_MASK; // PLL'i Aktive Et

        while (!(CCM_ANALOG->PLL_SYS & CCM_ANALOG_PLL_SYS_LOCK_MASK)){} //PLL Kilitlenene Kadar Bekle
        
        CCM_ANALOG->PLL_SYS_CLR = CCM_ANALOG_PLL_SYS_BYPASS_MASK; // PLL bypass disable
    } else {
        // PFD_528_FRAC Set ( PFDn ->  528MHz * 18 / FRAC )
        // ( PFD0 = 352MHz ), (  PFD1 = 594MHz ), (  PFD2 = 396MHz ), (  PFD3 = 297MHz )
        CCM_ANALOG->PFD_528 = CCM_ANALOG_PFD_528_PFD0_FRAC(27) | CCM_ANALOG_PFD_528_PFD1_FRAC(16) | 
                              CCM_ANALOG_PFD_528_PFD2_FRAC(24) | CCM_ANALOG_PFD_528_PFD3_FRAC(32) | 0x80808080;
    }

     // Hersey ayarlanip PLL2 aktif hale geldi. Artik PFD leri acabiliriz.
    CCM_ANALOG->PFD_528_CLR = CCM_ANALOG_PFD_528_PFD0_CLKGATE_MASK | CCM_ANALOG_PFD_528_PFD1_CLKGATE_MASK | 
                              CCM_ANALOG_PFD_528_PFD2_CLKGATE_MASK | CCM_ANALOG_PFD_528_PFD3_CLKGATE_MASK ;

}

void PLL_USB1_CLK_Init(void) {

    // PLL3 altindaki saatler. PLL3 PowerDown oncesi set etmek gerekiyor
    CCM_ANALOG->PFD_480_SET = CCM_ANALOG_PFD_480_PFD0_CLKGATE_MASK | CCM_ANALOG_PFD_480_PFD1_CLKGATE_MASK | 
                              CCM_ANALOG_PFD_480_PFD2_CLKGATE_MASK | CCM_ANALOG_PFD_480_PFD3_CLKGATE_MASK ;

    if((CCM_ANALOG->PLL_USB1 & CCM_ANALOG_PLL_USB1_DIV_SELECT_MASK)) {
        CCM_ANALOG->PLL_USB1_SET = CCM_ANALOG_PLL_USB1_BYPASS_MASK;

        CCM_ANALOG->PLL_USB1_CLR = CCM_ANALOG_PLL_USB1_POWER_MASK | CCM_ANALOG_PLL_USB1_DIV_SELECT_MASK; // Neden digerlerinde powerdown iken bunda powerup bilmiyorum.

        CCM_ANALOG->PLL_USB1_SET = CCM_ANALOG_PLL_USB1_DIV_SELECT(0);
        
        // PFD_480_FRAC Set ( PFDn ->  480MHz * 18 / FRAC )
        // ( PFD0 = 720 ), ( PFD1 = 664.6153.. ), ( PFD2 = 508.2352.. ), ( PFD3 = 454.7368.. ) Bunlar Reference Manueldeki Degerler
        CCM_ANALOG->PFD_480 = CCM_ANALOG_PFD_480_PFD0_FRAC(12) | CCM_ANALOG_PFD_480_PFD1_FRAC(13) | 
                              CCM_ANALOG_PFD_480_PFD2_FRAC(17) | CCM_ANALOG_PFD_480_PFD3_FRAC(19) | 0x80808080;

        CCM_ANALOG->PLL_USB1_SET = CCM_ANALOG_PLL_USB1_POWER_MASK | CCM_ANALOG_PLL_USB1_ENABLE_MASK;

        while(!(CCM_ANALOG->PLL_USB1 & CCM_ANALOG_PLL_USB1_LOCK_MASK)){}

        CCM_ANALOG->PLL_USB1_CLR = CCM_ANALOG_PLL_USB1_BYPASS_MASK;
    } else {
        // PFD_480_FRAC Set ( PFDn ->  480MHz * 18 / FRAC )
        // ( PFD0 = 720 ), ( PFD1 = 664.6153.. ), ( PFD2 = 508.2352.. ), ( PFD3 = 454.7368.. ) Bunlar Reference Manueldeki Degerler
        CCM_ANALOG->PFD_480 = CCM_ANALOG_PFD_480_PFD0_FRAC(12) | CCM_ANALOG_PFD_480_PFD1_FRAC(13) | 
                              CCM_ANALOG_PFD_480_PFD2_FRAC(17) | CCM_ANALOG_PFD_480_PFD3_FRAC(19) | 0x80808080;
    }

    CCM_ANALOG->PFD_480_CLR = CCM_ANALOG_PFD_480_PFD0_CLKGATE_MASK | CCM_ANALOG_PFD_480_PFD1_CLKGATE_MASK | 
                              CCM_ANALOG_PFD_480_PFD2_CLKGATE_MASK | CCM_ANALOG_PFD_480_PFD3_CLKGATE_MASK ;

}

void PLL_VIDEO_CLK_Init(void) {
    // PLL5 Ayarlanacak
    // TRACE_CLK icin lazim
}

void USDHC1_CLK_Init(void) {
    if((CCM->CSCMR1 & CCM_CSCMR1_USDHC1_CLK_SEL_MASK) != CCM_CSCMR1_USDHC1_CLK_SEL(0)) {
        CCM->CSCMR1 = ( CCM->CSCMR1 & ~CCM_CSCMR1_USDHC1_CLK_SEL_MASK ) | CCM_CSCMR1_USDHC1_CLK_SEL(0);
        (void)CCM->CSCMR1;
    }

    CCM->CSCDR1 = ( CCM->CSCDR1 & ~CCM_CSCDR1_USDHC1_PODF_MASK ) | CCM_CSCDR1_USDHC1_PODF(5);
    (void)CCM->CSCDR1;
}

void USDHC2_CLK_Init(void) {
    if((CCM->CSCMR1 & CCM_CSCMR1_USDHC2_CLK_SEL_MASK) != CCM_CSCMR1_USDHC2_CLK_SEL(0)) {
        CCM->CSCMR1 = ( CCM->CSCMR1 & ~CCM_CSCMR1_USDHC2_CLK_SEL_MASK ) | CCM_CSCMR1_USDHC2_CLK_SEL(0);
        (void)CCM->CSCMR1;
    }

    CCM->CSCDR1 = ( CCM->CSCDR1 & ~CCM_CSCDR1_USDHC2_PODF_MASK ) | CCM_CSCDR1_USDHC2_PODF(5);
    (void)CCM->CSCDR1;
}

void CSI_CLK_Init(void) {
    if((CCM->CSCDR3 & CCM_CSCDR3_CSI_CLK_SEL_MASK) != CCM_CSCDR3_CSI_CLK_SEL(2)) {
        CCM->CSCDR3 = ( CCM->CSCDR3 & ~CCM_CSCDR3_CSI_CLK_SEL_MASK ) | CCM_CSCDR3_CSI_CLK_SEL(2);
        (void)CCM->CSCDR3;
    }

    CCM->CSCDR3 = ( CCM->CSCDR3 & ~CCM_CSCDR3_CSI_PODF_MASK ) | CCM_CSCDR3_CSI_PODF(1);
    (void)CCM->CSCDR3;
}

void LPSPI_CLK_Init(void) {
    if((CCM->CBCMR & CCM_CBCMR_LPSPI_CLK_SEL_MASK) != CCM_CBCMR_LPSPI_CLK_SEL(2)) {
        CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_LPSPI_CLK_SEL_MASK ) | CCM_CBCMR_LPSPI_CLK_SEL(2);
        (void)CCM->CBCMR;
    }

    CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_LPSPI_PODF_MASK ) | CCM_CBCMR_LPSPI_PODF(7);
    (void)CCM->CBCMR;
}

void TRACE_CLK_Init(void) {
    if((CCM->CBCMR & CCM_CBCMR_TRACE_CLK_SEL_MASK) != CCM_CBCMR_TRACE_CLK_SEL(0)) {
        CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_TRACE_CLK_SEL_MASK ) | CCM_CBCMR_TRACE_CLK_SEL(0);
        (void)CCM->CBCMR;
    }

    CCM->CSCDR1 = ( CCM->CSCDR1 & ~CCM_CSCDR1_TRACE_PODF_MASK ) | CCM_CSCDR1_TRACE_PODF(3);
    (void)CCM->CSCDR1;
}

void LPI2C_CLK_Init(void) {
    if((CCM->CSCDR2 & CCM_CSCDR2_LPI2C_CLK_SEL_MASK) != CCM_CSCDR2_LPI2C_CLK_SEL(0)) {
        CCM->CSCDR2 = ( CCM->CSCDR2 & ~CCM_CSCDR2_LPI2C_CLK_SEL_MASK ) | CCM_CSCDR2_LPI2C_CLK_SEL(0);
        (void)CCM->CSCDR2;
    }

    CCM->CSCDR2 = ( CCM->CSCDR2 & ~CCM_CSCDR2_LPI2C_CLK_PODF_MASK ) | CCM_CSCDR2_LPI2C_CLK_PODF(0);
    (void)CCM->CSCDR2;
}

void CAN_CLK_Init(void) {
    if((CCM->CSCMR2 & CCM_CSCMR2_CAN_CLK_SEL_MASK) != CCM_CSCMR2_CAN_CLK_SEL(2)) {
        CCM->CSCMR2 = ( CCM->CSCMR2 & ~CCM_CSCMR2_CAN_CLK_SEL_MASK ) | CCM_CSCMR2_CAN_CLK_SEL(2);
        (void)CCM->CSCMR2;
    }

    CCM->CSCMR2 = ( CCM->CSCMR2 & ~CCM_CSCMR2_CAN_CLK_PODF_MASK ) | CCM_CSCMR2_CAN_CLK_PODF(1);
    (void)CCM->CSCMR2;
}

void UART_CLK_Init(void) {
    if((CCM->CSCDR1 & CCM_CSCDR1_UART_CLK_SEL_MASK) != CCM_CSCDR1_UART_CLK_SEL(1)) {
        CCM->CSCDR1 = ( CCM->CSCDR1 & ~CCM_CSCDR1_UART_CLK_SEL_MASK ) | CCM_CSCDR1_UART_CLK_SEL(1);
        (void)CCM->CSCDR1;
    }

    CCM->CSCDR1 = ( CCM->CSCDR1 & ~CCM_CSCDR1_UART_CLK_PODF_MASK ) | CCM_CSCDR1_UART_CLK_PODF(0);
    (void)CCM->CSCDR1;
}

void LCDIF_CLK_Init(void) {
    if((CCM->CSCDR2 & CCM_CSCDR2_LCDIF_PRE_CLK_SEL_MASK) != CCM_CSCDR2_LCDIF_PRE_CLK_SEL(2)) {
        CCM->CSCDR2 = ( CCM->CSCDR2 & ~CCM_CSCDR2_LCDIF_PRE_CLK_SEL_MASK ) | CCM_CSCDR2_LCDIF_PRE_CLK_SEL(2);
        (void)CCM->CSCDR2;
    }

    CCM->CSCDR2 = ( CCM->CSCDR2 & ~CCM_CSCDR2_LCDIF_PRED_MASK ) | CCM_CSCDR2_LCDIF_PRED(1);
    (void)CCM->CSCDR2;

    CCM->CBCMR = ( CCM->CBCMR & ~CCM_CBCMR_LCDIF_PODF_MASK )  | CCM_CBCMR_LCDIF_PODF(1);
    (void)CCM->CBCMR;
}