#include "Teensy_Digital.h"

Pins Teensy_Pins[55] = {
    {PIN0_BIT , PIN0_MUX , PIN0_PAD , PIN0_MUX_MODE_MASK , PIN0_GPIO },
    {PIN1_BIT , PIN1_MUX , PIN1_PAD , PIN1_MUX_MODE_MASK , PIN1_GPIO },
    {PIN2_BIT , PIN2_MUX , PIN2_PAD , PIN2_MUX_MODE_MASK , PIN2_GPIO },
    {PIN3_BIT , PIN3_MUX , PIN3_PAD , PIN3_MUX_MODE_MASK , PIN3_GPIO },
    {PIN4_BIT , PIN4_MUX , PIN4_PAD , PIN4_MUX_MODE_MASK , PIN4_GPIO },
    {PIN5_BIT , PIN5_MUX , PIN5_PAD , PIN5_MUX_MODE_MASK , PIN5_GPIO },
    {PIN6_BIT , PIN6_MUX , PIN6_PAD , PIN6_MUX_MODE_MASK , PIN6_GPIO },
    {PIN7_BIT , PIN7_MUX , PIN7_PAD , PIN7_MUX_MODE_MASK , PIN7_GPIO },
    {PIN8_BIT , PIN8_MUX , PIN8_PAD , PIN8_MUX_MODE_MASK , PIN8_GPIO },
    {PIN9_BIT , PIN9_MUX , PIN9_PAD , PIN9_MUX_MODE_MASK , PIN9_GPIO },
    {PIN10_BIT, PIN10_MUX, PIN10_PAD, PIN10_MUX_MODE_MASK, PIN10_GPIO},
    {PIN11_BIT, PIN11_MUX, PIN11_PAD, PIN11_MUX_MODE_MASK, PIN11_GPIO},
    {PIN12_BIT, PIN12_MUX, PIN12_PAD, PIN12_MUX_MODE_MASK, PIN12_GPIO},
    {PIN13_BIT, PIN13_MUX, PIN13_PAD, PIN13_MUX_MODE_MASK, PIN13_GPIO},
    {PIN14_BIT, PIN14_MUX, PIN14_PAD, PIN14_MUX_MODE_MASK, PIN14_GPIO},
    {PIN15_BIT, PIN15_MUX, PIN15_PAD, PIN15_MUX_MODE_MASK, PIN15_GPIO},
    {PIN16_BIT, PIN16_MUX, PIN16_PAD, PIN16_MUX_MODE_MASK, PIN16_GPIO},
    {PIN17_BIT, PIN17_MUX, PIN17_PAD, PIN17_MUX_MODE_MASK, PIN17_GPIO},
    {PIN18_BIT, PIN18_MUX, PIN18_PAD, PIN18_MUX_MODE_MASK, PIN18_GPIO},
    {PIN19_BIT, PIN19_MUX, PIN19_PAD, PIN19_MUX_MODE_MASK, PIN19_GPIO},
    {PIN20_BIT, PIN20_MUX, PIN20_PAD, PIN20_MUX_MODE_MASK, PIN20_GPIO},
    {PIN21_BIT, PIN21_MUX, PIN21_PAD, PIN21_MUX_MODE_MASK, PIN21_GPIO},
    {PIN22_BIT, PIN22_MUX, PIN22_PAD, PIN22_MUX_MODE_MASK, PIN22_GPIO},
    {PIN23_BIT, PIN23_MUX, PIN23_PAD, PIN23_MUX_MODE_MASK, PIN23_GPIO},
    {PIN24_BIT, PIN24_MUX, PIN24_PAD, PIN24_MUX_MODE_MASK, PIN24_GPIO},
    {PIN25_BIT, PIN25_MUX, PIN25_PAD, PIN25_MUX_MODE_MASK, PIN25_GPIO},
    {PIN26_BIT, PIN26_MUX, PIN26_PAD, PIN26_MUX_MODE_MASK, PIN26_GPIO},
    {PIN27_BIT, PIN27_MUX, PIN27_PAD, PIN27_MUX_MODE_MASK, PIN27_GPIO},
    {PIN28_BIT, PIN28_MUX, PIN28_PAD, PIN28_MUX_MODE_MASK, PIN28_GPIO},
    {PIN29_BIT, PIN29_MUX, PIN29_PAD, PIN29_MUX_MODE_MASK, PIN29_GPIO},
    {PIN30_BIT, PIN30_MUX, PIN30_PAD, PIN30_MUX_MODE_MASK, PIN30_GPIO},
    {PIN31_BIT, PIN31_MUX, PIN31_PAD, PIN31_MUX_MODE_MASK, PIN31_GPIO},
    {PIN32_BIT, PIN32_MUX, PIN32_PAD, PIN32_MUX_MODE_MASK, PIN32_GPIO},
    {PIN33_BIT, PIN33_MUX, PIN33_PAD, PIN33_MUX_MODE_MASK, PIN33_GPIO},
    {PIN34_BIT, PIN34_MUX, PIN34_PAD, PIN34_MUX_MODE_MASK, PIN34_GPIO},
    {PIN35_BIT, PIN35_MUX, PIN35_PAD, PIN35_MUX_MODE_MASK, PIN35_GPIO},
    {PIN36_BIT, PIN36_MUX, PIN36_PAD, PIN36_MUX_MODE_MASK, PIN36_GPIO},
    {PIN37_BIT, PIN37_MUX, PIN37_PAD, PIN37_MUX_MODE_MASK, PIN37_GPIO},
    {PIN38_BIT, PIN38_MUX, PIN38_PAD, PIN38_MUX_MODE_MASK, PIN38_GPIO},
    {PIN39_BIT, PIN39_MUX, PIN39_PAD, PIN39_MUX_MODE_MASK, PIN39_GPIO},
    {PIN40_BIT, PIN40_MUX, PIN40_PAD, PIN40_MUX_MODE_MASK, PIN40_GPIO},
    {PIN41_BIT, PIN41_MUX, PIN41_PAD, PIN41_MUX_MODE_MASK, PIN41_GPIO},
    {PIN42_BIT, PIN42_MUX, PIN42_PAD, PIN42_MUX_MODE_MASK, PIN42_GPIO},
    {PIN43_BIT, PIN43_MUX, PIN43_PAD, PIN43_MUX_MODE_MASK, PIN43_GPIO},
    {PIN44_BIT, PIN44_MUX, PIN44_PAD, PIN44_MUX_MODE_MASK, PIN44_GPIO},
    {PIN45_BIT, PIN45_MUX, PIN45_PAD, PIN45_MUX_MODE_MASK, PIN45_GPIO},
    {PIN46_BIT, PIN46_MUX, PIN46_PAD, PIN46_MUX_MODE_MASK, PIN46_GPIO},
    {PIN47_BIT, PIN47_MUX, PIN47_PAD, PIN47_MUX_MODE_MASK, PIN47_GPIO},
    {PIN48_BIT, PIN48_MUX, PIN48_PAD, PIN48_MUX_MODE_MASK, PIN48_GPIO},
    {PIN49_BIT, PIN49_MUX, PIN49_PAD, PIN49_MUX_MODE_MASK, PIN49_GPIO},
    {PIN50_BIT, PIN50_MUX, PIN50_PAD, PIN50_MUX_MODE_MASK, PIN50_GPIO},
    {PIN51_BIT, PIN51_MUX, PIN51_PAD, PIN51_MUX_MODE_MASK, PIN51_GPIO},
    {PIN52_BIT, PIN52_MUX, PIN52_PAD, PIN52_MUX_MODE_MASK, PIN52_GPIO},
    {PIN53_BIT, PIN53_MUX, PIN53_PAD, PIN53_MUX_MODE_MASK, PIN53_GPIO},
    {PIN54_BIT, PIN54_MUX, PIN54_PAD, PIN54_MUX_MODE_MASK, PIN54_GPIO}
};

void pinMode(uint8_t pin, uint8_t mode) {
    
    if(pin>=55) return;

    Pins* p = Teensy_Pins + pin;

    if(mode == OUTPUT || mode == OUTPUT_OPENDRAIN) {

        p->gpio->GDIR |= (1 << p->bit);

        if(mode == OUTPUT) {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6);
        } else { // OUTPUT_OPENDRAIN
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_ODE_MASK;
        }

    } else {

        p->gpio->GDIR &= ~(1 << p->bit);
        
        if(mode == INPUT) {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6);
        } else if(mode == INPUT_PULLUP) {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_PKE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUS(3) | IOMUXC_SW_PAD_CTL_PAD_HYS_MASK;
        } else if(mode == INPUT_PULLDOWN) {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_PKE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUS(0) | IOMUXC_SW_PAD_CTL_PAD_HYS_MASK;
        } else { // INPUT_DISABLE
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_HYS_MASK;
        }
        
    }

    IOMUXC->SW_MUX_CTL_PAD[p->mux] = ( IOMUXC->SW_MUX_CTL_PAD[p->mux] & ~(p->mux_mask) ) | 0x5;
}

void digitalToggle(uint8_t pin) {
    // Bu fonksiyon olabildigince kullanilmamali.
    if(pin>=55) return;

    Pins* p = Teensy_Pins + pin;

    p->gpio->DR_TOGGLE  = 1 << p->bit;
}

void digitalWrite(uint8_t pin, uint8_t val) {
    // Bu fonksiyon olabildigince kullanilmamali.
    if(pin>=55) return;

    Pins* p = Teensy_Pins + pin;

    if(p->gpio->GDIR & (1 << p->bit)) {
        if(val) {
            p->gpio->DR_SET   = 1 << p->bit;
        } else {
            p->gpio->DR_CLEAR = 1 << p->bit;
        }
    } else {
        if(val) {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_PKE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUS(3) | IOMUXC_SW_PAD_CTL_PAD_HYS_MASK;
        } else {
            IOMUXC->SW_PAD_CTL_PAD[p->pad] = IOMUXC_SW_PAD_CTL_PAD_DSE(6) | IOMUXC_SW_PAD_CTL_PAD_PKE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUE_MASK | IOMUXC_SW_PAD_CTL_PAD_PUS(0) | IOMUXC_SW_PAD_CTL_PAD_HYS_MASK;
        }
    }
}

uint8_t digitalRead(uint8_t pin) {
    // Bu fonksiyon olabildigince kullanilmamali.
    if(pin>=55) return 0;

    Pins* p = Teensy_Pins + pin;

    return (p->gpio->PSR & (1 << p->bit)) ? 1 : 0;
}